package com.yiping.sys.model;

// Generated 2016/1/19 �U�� 10:34:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.yiping.order.model.Order100;
import com.yiping.order.model.Order101;
import com.yiping.stock.model.Stock100;

/**
 * SysStatus100 generated by hbm2java
 */
@Entity
@Table(name = "sys_status100", catalog = "yiping")
public class SysStatus100 implements java.io.Serializable {

	private int sysStatus100Id;
	private String columnName;
	private String statusName;
	private String statusDetail;

	public SysStatus100() {
	}

	public SysStatus100(String columnName, String statusName) {
		this.columnName = columnName;
		this.statusName = statusName;
	}

	public SysStatus100(String columnName, String statusName,
			String statusDetail, Set<Stock100> stock100s,
			Set<Order101> order101s, Set<Order100> order100s) {
		this.columnName = columnName;
		this.statusName = statusName;
		this.statusDetail = statusDetail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SYS_STATUS100_ID", unique = true, nullable = false)
	public int getSysStatus100Id() {
		return this.sysStatus100Id;
	}

	public void setSysStatus100Id(int sysStatus100Id) {
		this.sysStatus100Id = sysStatus100Id;
	}

	@Column(name = "COLUMN_NAME", nullable = false)
	public String getColumnName() {
		return this.columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}

	@Column(name = "STATUS_NAME", nullable = false)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	@Column(name = "STATUS_DETAIL")
	public String getStatusDetail() {
		return this.statusDetail;
	}

	public void setStatusDetail(String statusDetail) {
		this.statusDetail = statusDetail;
	}
}
