package com.yiping.order.model;

// Generated 2016/1/19 �U�� 10:34:22 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.yiping.product.model.Product100;
import com.yiping.sys.model.SysStatus100;

/**
 * Order101 generated by hbm2java
 */
@Entity
@Table(name = "order101", catalog = "yiping")
public class Order101 implements java.io.Serializable {

	private int order101Id;
	private Product100 product100;
	private Order100 order100;
	private SysStatus100 productStatus;
	private Integer productNum;

	public Order101() {
	}

	public Order101(Product100 product100, Order100 order100,
			SysStatus100 productStatus, Integer productNum) {
		this.product100 = product100;
		this.order100 = order100;
		this.productStatus = productStatus;
		this.productNum = productNum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ORDER101_ID", unique = true, nullable = false)
	public int getOrder101Id() {
		return this.order101Id;
	}

	public void setOrder101Id(int order101Id) {
		this.order101Id = order101Id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PRODUCT100_ID", nullable = false)
	public Product100 getProduct100() {
		return this.product100;
	}

	public void setProduct100(Product100 product100) {
		this.product100 = product100;
	}
	
	@JsonManagedReference
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ORDER100_ID", nullable = false)
	public Order100 getOrder100() {
		return this.order100;
	}

	public void setOrder100(Order100 order100) {
		this.order100 = order100;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PRODUCT_STATUS", nullable = false)
	public SysStatus100 getProductStatus() {
		return this.productStatus;
	}

	public void setProductStatus(SysStatus100 sysStatus100) {
		this.productStatus = sysStatus100;
	}

	@Column(name = "PRODUCT_NUM", nullable = false)
	public Integer getProductNum() {
		return this.productNum;
	}

	public void setProductNum(Integer productNum) {
		this.productNum = productNum;
	}

}
