package com.yiping.customer.model;

// Generated 2016/1/19 �U�� 10:34:22 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.yiping.order.model.Order100;

/**
 * Customer100 generated by hbm2java
 */
@Entity
@Table(name = "customer100", catalog = "yiping")
public class Customer100 implements java.io.Serializable {

	private int customer100Id;
	private String cusName;
	private String cusPhoneNum;
	private Integer cusSex;
	private Set<Order100> order100s = new HashSet<Order100>(0);

	public Customer100() {
	}

	public Customer100(String cusName, String cusPhoneNum) {
		this.cusName = cusName;
		this.cusPhoneNum = cusPhoneNum;
	}

	public Customer100(String cusName, String cusPhoneNum, Integer cusSex,
			Set<Order100> order100s) {
		this.cusName = cusName;
		this.cusPhoneNum = cusPhoneNum;
		this.cusSex = cusSex;
		this.order100s = order100s;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CUSTOMER100_ID", unique = true, nullable = false)
	public int getCustomer100Id() {
		return this.customer100Id;
	}

	public void setCustomer100Id(int customer100Id) {
		this.customer100Id = customer100Id;
	}

	@Column(name = "CUS_NAME", nullable = false)
	public String getCusName() {
		return this.cusName;
	}

	public void setCusName(String cusName) {
		this.cusName = cusName;
	}

	@Column(name = "CUS_PHONE_NUM", nullable = false)
	public String getCusPhoneNum() {
		return this.cusPhoneNum;
	}

	public void setCusPhoneNum(String cusPhoneNum) {
		this.cusPhoneNum = cusPhoneNum;
	}

	@Column(name = "CUS_SEX")
	public Integer getCusSex() {
		return this.cusSex;
	}

	public void setCusSex(Integer cusSex) {
		this.cusSex = cusSex;
	}
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer100")
	public Set<Order100> getOrder100s() {
		return this.order100s;
	}

	public void setOrder100s(Set<Order100> order100s) {
		this.order100s = order100s;
	}

}
