package com.yiping.product.model;

// Generated 2016/1/19 �U�� 10:34:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.yiping.order.model.Order101;
import com.yiping.stock.model.Stock101;

/**
 * Product100 generated by hbm2java
 */
@Entity
@Table(name = "product100", catalog = "yiping")
public class Product100 implements java.io.Serializable {

	private int product100Id;
	private String productName;
	private Integer productPrice;
	private String productDetail;
	private Set<Stock101> stock101s = new HashSet<Stock101>(0);
	private Set<Order101> order101s = new HashSet<Order101>(0);

	public Product100() {
	}

	public Product100(String productName, Integer productPrice) {
		this.productName = productName;
		this.productPrice = productPrice;
	}

	public Product100(String productName, Integer productPrice,
			String productDetail, Set<Stock101> stock101s,
			Set<Order101> order101s) {
		this.productName = productName;
		this.productPrice = productPrice;
		this.productDetail = productDetail;
		this.stock101s = stock101s;
		this.order101s = order101s;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PRODUCT100_ID", unique = true, nullable = false)
	public int getProduct100Id() {
		return this.product100Id;
	}

	public void setProduct100Id(int product100Id) {
		this.product100Id = product100Id;
	}

	@Column(name = "PRODUCT_NAME", nullable = false)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "PRODUCT_PRICE", nullable = false)
	public Integer getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(Integer productPrice) {
		this.productPrice = productPrice;
	}

	@Column(name = "PRODUCT_DETAIL")
	public String getProductDetail() {
		return this.productDetail;
	}

	public void setProductDetail(String productDetail) {
		this.productDetail = productDetail;
	}
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product100")
	public Set<Stock101> getStock101s() {
		return this.stock101s;
	}

	public void setStock101s(Set<Stock101> stock101s) {
		this.stock101s = stock101s;
	}
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product100")
	public Set<Order101> getOrder101s() {
		return this.order101s;
	}

	public void setOrder101s(Set<Order101> order101s) {
		this.order101s = order101s;
	}

}
