package com.yiping.stock.model;

// Generated 2016/1/19 �U�� 10:34:22 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.yiping.order.model.Order100;
import com.yiping.sys.model.SysStatus100;

/**
 * Stock100 generated by hbm2java
 */
@Entity
@Table(name = "stock100", catalog = "yiping")
public class Stock100 implements java.io.Serializable {

	private int stock100Id;
	private Order100 order100;
	private SysStatus100 stockType;
	private Date createTime;
	private Set<Stock101> stock101s = new HashSet<Stock101>(0);

	public Stock100() {
	}

	public Stock100(SysStatus100 stockType, Date createTime) {
		this.stockType = stockType;
		this.createTime = createTime;
	}

	public Stock100(Order100 order100, SysStatus100 stockType,
			Date createTime, Set<Stock101> stock101s) {
		this.order100 = order100;
		this.stockType = stockType;
		this.createTime = createTime;
		this.stock101s = stock101s;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "STOCK100_ID", unique = true, nullable = false)
	public int getStock100Id() {
		return this.stock100Id;
	}

	public void setStock100Id(int stock100Id) {
		this.stock100Id = stock100Id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ORDER100_ID")
	public Order100 getOrder100() {
		return this.order100;
	}

	public void setOrder100(Order100 order100) {
		this.order100 = order100;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "STOCK_TYPE", nullable = false)
	public SysStatus100 getStockType() {
		return this.stockType;
	}

	public void setStockType(SysStatus100 stockType) {
		this.stockType = stockType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 10)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
	@JsonBackReference
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "stock100", cascade = CascadeType.ALL)
	public Set<Stock101> getStock101s() {
		return this.stock101s;
	}

	public void setStock101s(Set<Stock101> stock101s) {
		this.stock101s = stock101s;
	}
	
	public void addStockDetail(Stock101 stock101){
		stock101s.add(stock101);
		if(stock101.getStock100() != this){
			stock101.setStock100(this);
		}
	}

}
