package com.yiping.stock.model;

// Generated 2016/2/6 �U�� 09:16:28 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.yiping.product.model.Product100;

/**
 * Stock200 generated by hbm2java
 */
@Entity
@Table(name = "stock200", catalog = "yiping")
public class Stock200 implements java.io.Serializable {

	private int stock200Id;
	private Product100 product100;
	private Date updatedate;
	private Integer stockNum;

	public Stock200() {
	}

	public Stock200(Product100 product100, Date updatedate) {
		this.product100 = product100;
		this.updatedate = updatedate;
	}

	public Stock200(Product100 product100, Date updatedate, Integer stockNum) {
		this.product100 = product100;
		this.updatedate = updatedate;
		this.stockNum = stockNum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "STOCK200_ID", unique = true, nullable = false)
	public int getStock200Id() {
		return this.stock200Id;
	}

	public void setStock200Id(int stock200Id) {
		this.stock200Id = stock200Id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT100_ID", nullable = false)
	public Product100 getProduct100() {
		return this.product100;
	}

	public void setProduct100(Product100 product100) {
		this.product100 = product100;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEDATE", nullable = false, length = 19)
	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	@Column(name = "STOCK_NUM")
	public Integer getStockNum() {
		return this.stockNum;
	}

	public void setStockNum(Integer stockNum) {
		this.stockNum = stockNum;
	}

}
